apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-red-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-red-operator
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["create", "patch", "get", "list", "watch", "delete"] 
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "patch", "get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "patch", "get", "list", "watch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create", "patch", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-red-operator
  namespace: default
subjects:
- kind: ServiceAccount
  name: node-red-operator
  namespace: default
roleRef:
  kind: Role
  name: node-red-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red.hardill.me.uk
  template:
    metadata:
      labels:
        app: node-red.hardill.me.uk
    spec:
      serviceAccountName: node-red-operator
      containers:
      - name: node-red
        image: containers.hardill.me.uk/testing/node-red-operator:latest
        imagePullPolicy: Always
        ports:
        - name: https
          containerPort: 8443
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: node-red
spec:
  type: NodePort
  selector:
    app: node-red.hardill.me.uk
  ports:
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: node-red.hardill.me.uk
webhooks:
- name: node-red.hardill.me.uk
  # namespaceSelector:
  #   matchExpressions:
  #   - key: kubernetes.io/metadata.name
  #     operator: In
  #     values: 
  #       - groupOne
  rules:
  - apiGroups:   [ "k8s.hardill.me.uk" ]
    apiVersions: [ "v1", "k8s.hardill.me.uk/v1" ]
    resources:   [ "node-reds" ]
    operations:  [ "CREATE", "DELETE" ]
    scope:       Namespaced
  clientConfig:
    service:
      namespace: default
      name: node-red
      path: /create
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZzekNDQTV1Z0F3SUJBZ0lVYlJxSHkrRTc5anNlM2tnWDYweE52UTY4cVFvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2FURUxNQWtHQTFVRUJoTUNSMEl4R0RBV0JnTlZCQWdNRDBkc2IzVmpaWE4wWlhKemFHbHlaVEVpTUNBRwpBMVVFQ2d3WlNHRnlaR2xzYkNCVVpXTm9ibTlzYjJkcFpYTWdUSFJrTGpFUE1BMEdBMVVFQ3d3R1N6aHpJRU5CCk1Rc3dDUVlEVlFRRERBSkRRVEFlRncweU5ERXlNak14TWpBM05UTmFGdzB5TlRBeE1qSXhNakEzTlROYU1Ha3gKQ3pBSkJnTlZCQVlUQWtkQ01SZ3dGZ1lEVlFRSURBOUhiRzkxWTJWemRHVnljMmhwY21VeElqQWdCZ05WQkFvTQpHVWhoY21ScGJHd2dWR1ZqYUc1dmJHOW5hV1Z6SUV4MFpDNHhEekFOQmdOVkJBc01Ca3M0Y3lCRFFURUxNQWtHCkExVUVBd3dDUTBFd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUURES2xjdmUwY0kKWmF2WGhDVFF3bEVsYi9rVGR0dTNUSklFV1I5UXVvL25yVDB5SWs1QTlLYkFjYWRDTGNSZHFMYUF3Q004ai9SdAowdGR2K0hiQ1F0U21mOFJGTXN1NlNRMk92bkRBTGRyRXVEM0wzOEdibXh0TGNrRVZYOHpnYUZueGpFN0FWUjZECm95WFZweDFtTXMvT05WRXdXQ0I4bHByNzVHQS9GMDAyOE1lWVRPYXc2SEdUMGMyRmR0Z1Q3d1dRV2l5VlJReDEKeXRZaEZEU2k3RXR4andhQnpYalhVTWsyMC9aN0ZiYjhobW5zbnZyZk41QksvWjNlbFh4VER5MEFBd3c2T3dnNApycTk2VFgxbEJoNFJzaXdwSnlFeGFUNEtzeE1NQkdwREhST3JNS3AwczR2RHpwOUV4Q2FqbS84MjZBSFUrYzg3CkRvdmREN045WE9yRHozWENSc3JwR3B4YzczN2VKUnpTUjJTbEk2bEtyeERNMjFINllZSGphTlpJV01tUDg5bWYKU2ZjbHVjY3BINFMxcTF5cVRxR2hmZjEyK1JPNUFmTXBsak5BTjhja1MySDhpVHdib3FoTXA5UGJKdmg1M0tISQpVR3V3YjVIUkgvTEZ5UmZTajByNXNDV2Y5ZUVpQmJ0RVhRRk1DWGs1cDl3c2pZWVUwUkhWSzVwK09vVXI3Q3NiCm9rN0ZHRDU2VXJrajgvSUI3anAwZVFSdllqSVpIRjZKVTlxbWE3WURaYjlSUWQ0ekNEUGJrNmRYaTJRTEJxaloKQWJQNzFNNFhWQkFYTDZvcWF5YTZnREZYTXpkYlV0MHpmNkVla2JkMFN0M3dybyt6YVZQTEkxMnhZQzB3Sy9XcApZbjVYcjlFbUFDNjlCYWQ3SnJvR2syTHJsMjFvZW1kOVVRSURBUUFCbzFNd1VUQWRCZ05WSFE0RUZnUVVqOHN1CjcwNzVLWnh4aDh5bTMvQ1lWMW9ORFU4d0h3WURWUjBqQkJnd0ZvQVVqOHN1NzA3NUtaeHhoOHltMy9DWVYxb04KRFU4d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQU1IZFRCRW1sc3ptdwpTWW1pZkFHc2Rya1dBQU0zM1RjelFVQWpHU1NkK0tqUU9PVm9RZWpkcDB3dkliSUJlUWpxeEk2MERoOTlvQ0pqCllaWWdsbzFtQUI2bDdzWHJTWWkrckRURHhrY3h1MWo2RUlKRnlOOSs3MVZBQWcxVzdEemxnZ2hlcExHRC84YjAKQ2RkZERZSUFZUkhyZXY4Qzk4eVRUblIrS1pvTFp2T3g3RjVxU01XaWw1SmlnNndUNkx5cGVETEQ3c1RCTTJkZQp1MWs2Rk5LTGhTc0VRTjJBZ2g1NHpLVTlBUGRNbVlRWWNVSG54QUxCZTNKbnBXTjBpTDNod1VyNzN5enh0WEJTCkxIQ2JPWGJvK2xLaFE4TGY5MWdoU2xOOWxVTW1JdldQSEQvYWJFajR6djBhL0cwM0FpRlNDRFZHdHhmN1FTSmwKR0lDeGlRL3dIYzNOVXVVd1VpOEJVL21iYXU0bk84Q0NIaVQzcFBGcC9jZGkwUGdQczE3cTdNWENQb0xSYnhYTQo0eld0Uzh6Skw5cTFXNVg5MDlVM1JCZUpoL0EyS29ZU0VPSW12alh5V2ZadlBGY0E4QVErQmttc1R3N2ZZRThiCnZkUEd4STFJSUk5YlR0bC9VN25jRlFvUVB4VENwSkVObkFQZkM2OC9JUmNRZC9hWHMySzloN1BRYU1wYjRsYjYKK210ZTQ1TitHTFlhNU5rU0JGdGFFcnZJaWQ0QzRkMnJya250TEdXRExnZjJUczdpdzlZdGRwM2xVanFBY2tXaQo5Wm9hYUVud2JUUHZ0aGFkZHcxK1VaUHNNK0hPVmpzbm1uV2MwOWZ5ZndTUGxQL3pDTzVibWZ3R1RjWWdBbFB6ClVmeHIxUjRHdEN3UFdOTmo4Q0Fzd3I4NE5CajdYSEE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5
  reinvocationPolicy: "Never"