apiVersion: v1
kind: Service
metadata:
  name: node-red
spec:
  type: ExternalName
  externalName: 192.168.1.114
  ports:
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: node-red.hardill.me.uk
webhooks:
- name: node-red.hardill.me.uk
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values: 
        - groupOne
  rules:
  - apiGroups:   [ "k8s.hardill.me.uk" ]
    apiVersions: [ "v1", "k8s.hardill.me.uk" ]
    resources:   [ "node-reds" ]
    operations:  [ "CREATE" ]
    scope:       Namespaced
  clientConfig:
    service:
      namespace: default
      name: node-red
      path: /create
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZzekNDQTV1Z0F3SUJBZ0lVVGFPb0crTE9BcXA0Z1J4WW83VUhjOFlzTVo0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2FURUxNQWtHQTFVRUJoTUNSMEl4R0RBV0JnTlZCQWdNRDBkc2IzVmpaWE4wWlhKemFHbHlaVEVpTUNBRwpBMVVFQ2d3WlNHRnlaR2xzYkNCVVpXTm9ibTlzYjJkcFpYTWdUSFJrTGpFUE1BMEdBMVVFQ3d3R1N6aHpJRU5CCk1Rc3dDUVlEVlFRRERBSkRRVEFlRncweU1qRXlNREl5TXpFMk1UQmFGdzB5TXpBeE1ERXlNekUyTVRCYU1Ha3gKQ3pBSkJnTlZCQVlUQWtkQ01SZ3dGZ1lEVlFRSURBOUhiRzkxWTJWemRHVnljMmhwY21VeElqQWdCZ05WQkFvTQpHVWhoY21ScGJHd2dWR1ZqYUc1dmJHOW5hV1Z6SUV4MFpDNHhEekFOQmdOVkJBc01Ca3M0Y3lCRFFURUxNQWtHCkExVUVBd3dDUTBFd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUUNSMEV5d0w4MDMKaVBRNENQNkVKRmtQbENkYlJES1lNY3djTzNKbmExV2Y2ejVRL1M0QWdYK0U4ZUJoS3U3NzNScyt2Qlh5em5rcApTMVk3OGZLZ0R6S2VTSmVzY2pldHdzcDZMaEFGQzV5Q1U2bEVOUkNXMm5DSWhodUZHUW43bHgyNHhERHVGcjAvClRtK3ZDYmNOZ1Qyck14SlVMRHEvK256WWhuNFJ6dGFhcTZWb0hicTN4b1hMenV6dy9lN3FNaUdTMVRDQ1FlZloKeGpVbTkydzhFbk80VzVwTmJnck9hT1VxZ1pGVUxPWkI4Zm8vN2NWakt6djFnY3hVSTBWVjVPRlp5MGh0L1g5bQpqZWtZUWFYYnFQdnlsRlk0eHdzWmNWUGpmY0s3NnBpVEpQQTRwMkNLQmdwSmh4VXgxZi8rTVRLMHUvdERnT1dWCm44R042T2ZTUU9KeGxUem5MaDZGOWE3NlArK3diQ0R6ZFh5ekNBUE5XZUI3MEZxMUZCV29qMlZxTmVFeWhkVloKSy9WYnVZSjAzcUkxS3RaL0RNclFFTVlNZkdlRDJCYU9rY2ZKRkxWb0Y4UGRUUFBGU0JYMDZtckxGaGhuMkVoSworK0NSdU5Tamg4NzVFa1dpRVF1S3h1OFZlZjVESGN6c28xeFFZczNRaHhOMXh6WnpWYW9TZmtyS0VwMzJ6dVNJCk5UOTQxUEJJQTY5TDdSQmRaVExEY3hFd3Vtd1YvQlVUa01TSkE5VG1WY0M4bTJQcmZ6Nmd6Qlp0VjBBZnpWZXIKdG5xMGFNeFgwbGtCcUUxRmt2aG85SEdIRjJyY0VGaStJdGJlRi9RL1htWTJhYjFrZ0JVYmJHUGlFVWN1MkhBQgpCVmNNWit5TUM2RFpXSm03MnNGUHBCNDhGbjQvYWtjZ0J3SURBUUFCbzFNd1VUQWRCZ05WSFE0RUZnUVV0UUFrCndQWmtkVmNFMWY3QUNQOVBFNWdnOVZzd0h3WURWUjBqQkJnd0ZvQVV0UUFrd1Baa2RWY0UxZjdBQ1A5UEU1Z2cKOVZzd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQWZRSXkvWHhMZVQvaApyMktMalpzd3lQdC9La3VaTkg0T3ZFSnBDbk1nUWNNakVaT0srZ1FkUWxGeTd1bkcxZUJqT1NLRHhXVkZyRXVyCm42a3crSUR2Q2VISHJPUEk2cUdnYmFXdGpaSFp0S0F2RnBabnJyNzdjTWl5bFdXK2RNQitOaktxZTZ0M0xzbVIKU2gxMDdFN29HWDEvakZKQVhWaEhhdmh0MTB2VXpCV1FOMXBUQU8xTGRmMUo1WnhrZElEaExRUlFpWHhpWWhTWgpnVTdtdnNsZldtOHhIT1N2eTZKOHQ0VmdBc2REamo1ZEZjV29pRjhINFdIRmlzcWU3Z1FXUmM1WlFudW9hSEthClRPUnNocTF3NEVvTy9mOGpzODljK1NqczJKRWQ2bDhHYzFWZEpPT1VaK3FXSnAvb1plL3hUV21kMXB0S1BJN1MKRjhyZzROdUdySmpHYnRWakErbEtOWnEvZ1dHN214UVI1c0RLOG5uVVhqT1REalJ2Q2RCdDJRLzlvVHY5QnFCcAptRzEvSGhwTEpTazZEZHAyRlRkTHJIaGR1THRsUzdwZXdudlBGWldZaXIwZnV6MTkxeHdybVlDbkhzNzU4TVVICjgwZWNseFk2M3JHeDFlYjZteFdCTE9yTkN1eFpYOUhjbFk5dkN0V1E0ZkFGNVBHOWltZkFUVENQd3ljUzFlWWcKMyt2V09mN2EveWhTTFduUzgzK0lKN1NFeWhOYWg0OFhGdG9GQS9WbHBFem5iakx5RzFYenlTVEhyK0dxNElISApqQVJjNUlDVElJWWpOM0pYUElmMmNPc2s0dHczTGRaQVNXaW1JbDIyZTdjbTRWY2ZmN3RqeE1ST2RwNThUOXRLCjk1M3BubWVDajRRLytVb0FQb3VnVjdaNXdPWWJPZTA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5
  reinvocationPolicy: "Never"