apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: node-red.k8s.hardill.me.uk
spec:
  group: k8s.hardill.me.uk
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                flow:
                  description: The Node-RED flow to run
                  type: string
                settings:
                  description: The Node-RED settings.js
                  type: string
                nodes:
                  description: List on npm packages to install
                  type: arrays
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      version:
                        type: string
                      required: ["name", "version"]
          required: ["spec"]
  scope: Namespaced
  names:
    plural: node-reds
    singular: node-red
    kind: node-red
    shortNames:
      - nr