apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: random.hardill.me.uk
spec:
  group: random.hardill.me.uk
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              spec:
                seed:
                  type: integer
  scope: Namespaced
  names:
    plural: randoms
    singular: random
    kind: Random
    shortNames:
      - R
